### ISSUE TITLE
[Enhancement] Filter Resources to only show SAML Request/Response

### ISSUE THREAD

**Issue by ethanklitz** [simplesamlphp/SAML-tracer#24]
I troubleshoot SAML on sites with lots of GET/POST noise. Would really appreciate the 'Filter Resources' to only show SAML. Seems like IF this.request.saml could be added to 'isRequestVisible'. Wish I could do PR to demonstrate but not well versed in extension dev.

**Comment by tvdijen** [comment]
There are many useful GET/POST messages related to the SAML-flow that would be hidden if we did. For instance the SAML IDP discovery requests/responses would get lost.

We have instead greatly improved the filtering of _true_ resources to ensure no js/css/fonts/images show up in the tracer.
