### ISSUE TITLE
support for firefox keyboard-shortcuts

### ISSUE THREAD

**Issue by nand09** [simplesamlphp/SAML-tracer#60]
It would be good to have the ability to put a keyboard shortcut that will open the saml-tracer tool.

**Comment by khlr** [comment]
Hello Fernando!

Thank you for that feature suggestion! May I ask for your motivation for that feature? Do you start SAML-tracer so frequently that a keyboard shortcut would be a real benefit for you? I'm just asking because I didn't miss that feature yet.

**Comment by nand09** [comment]
Hi Jan, 

I tend to use it pretty often. I usually use it in a private tab and most of the times I open a private tab by using the keyboard so if I can save one click and open the tool while my hands are already on the keyboard then that would be nice.

**Comment by khlr** [comment]
Hi Fernando,

I will have a look into this (but it might take some time 😇)
Just a reminder for myself: https://stackoverflow.com/questions/18132873/chrome-commands-keyboard-shortcuts-not-working

**Comment by khlr** [comment]
I assigned the shortcut <kbd>ALT</kbd> + <kbd>SHIFT</kbd> + <kbd>S</kbd> to open SAML-tracer.

But please note [this restriction](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations):
> If a key combination is already used by the browser (like "Ctrl+P") or by an existing add-on, then you can't override it. You can define it, but your event handler will not be called when the user presses the key combination.

Hence chances are, that this will (or could) conflict other keyboard shortcuts...

However you can override this shortcut and define your own one:
Firefox: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
Chrome: chrome://extensions/shortcuts
