### ISSUE TITLE
Network Error with axios.js XHR GET requests

### ISSUE THREAD

**Issue by tlenex** [simplesamlphp/SAML-tracer#67]
This plugin causes Network Error with https://github.com/axios/axios `GET` requests that includes `Authentication` header. 

Please consider supporting cors headers if request is mapping or cutting off headers in some way.

Occurs in Chrome 79+

**Comment by khlr** [comment]
\*cough\* somehow this issue passed me by a bit. Sorry. 🙈
Is this still a current issue?

**Comment by tlenex** [comment]
Not anymore.
