### ISSUE TITLE
SAMLrequest not show

### ISSUE THREAD

**Issue by ggambini** [simplesamlphp/SAML-tracer#71]
Hello

Since last update (14 december ?), SAMLtracer on Firefox (78ESR and 95) dont show SAMLrequest, only SAMLresponse.

Regards, Gilian

**Comment by tvdijen** [comment]
I can confirm this

**Comment by khlr** [comment]
Seems to be related with the updated version of pako:

> Uncaught invalid stored block lengths

I just wonder why this doesn't occour when decoding a SAMLresponse... 🤔

Anyway... I will have a closer look later.
For the meantime I suggest using version 1.6 ... Sorry for this! 😐
https://addons.mozilla.org/firefox/addon/saml-tracer/versions/

**Comment by thijskh** [comment]
I have unpublished 1.7 at AMO for now.

**Comment by khlr** [comment]
This ist fixed in Version 1.7.1
